name: unirel
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab
  - pandas
  - widgetsnbextension
  - pip:
    - datasets
    - wandb
    # Intel XPU
    - torch==2.6.0+xpu --index-url https://download.pytorch.org/whl/xpu
    # NVidia CUDA
    # - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu121
    - -r requirements.txt
