name: unirel
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab
  - pandas
  - widgetsnbextension
  - pip:
    - wandb
    - torch==2.5.1 --index-url https://download.pytorch.org/whl/cu121
    - -r requirements.txt
