name: unirel
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pandas
  - pip:
    - datasets
    - wandb
    # Intel Arc A770
    - torch==2.6.0+xpu --index-url https://download.pytorch.org/whl/xpu
    # Intel XPU / iGPU
    # - torch==2.7.0.dev20250202+xpu --index-url https://download.pytorch.org/whl/test/xpu
    # NVidia CUDA
    # - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu121
    - -r requirements.txt
